#!/bin/bash

# Git aliases

alias gis='git status'
alias gial='git add -A'
alias gipsom='git push origin master'
alias giplom='git pull origin master'


# Letter aliases

alias c='clear'
alias e='exit'
alias l='ls'
alias n='nano'
alias t='gnome-terminal'
alias u='cd ..'

# Application aliases

alias sublime='/opt/sublime_text/sublime_text'


# File aliases

alias bprofile='nano ~/.bash_profile'
alias brc='nano ~/.bashrc'
alias baliases='nano ~/.bash_aliases'


# Stack aliases
stack-yesod-dev="stack --docker-run-args='--net=bridge --publish=3000:3000' exec -- yesod devel"
